version: '3.8'
services:
  db:
    image: postgres:16
    container_name: user_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB= usermanagement_studyzed
      - POSTGRES_USER= fmn
      - POSTGRES_PASSWORD= mrlionbyte
    ports:
      - "5435:5432"
  
  usermanagement:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: usermanagement
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8005:8000"
    depends_on:
      - db

volumes:
  db: